### ISSUE TITLE
Continuous animation better?

### ISSUE THREAD

**Issue by searchy2** [shadowfaxtech/proSwipeButton#1]
Amazing work! 

A quick consideration: 
Do you think it would be better to have the swipe continuously animate and give the user the ability to order just by tapping the button?
Swiping requires learning a new gesture and would cause some confusion. You don't want to confuse the user when they are about to give you money! 

I really like the swipe animation but I think buttons should be clicked and swipe should not be required. 

Great library so far!

**Comment by ishaansrm** [comment]
Hey thanks! Nice idea to have the arrows continuously animate. Will implement that in a future release. As for tapping, the animations might look a bit off. 
Let me see what can be done 👍

**Comment by ishaangarg** [comment]
Hey thanks! Nice idea to have the arrows continuously animate. Will implement that in a future release. As for tapping, the animations might look a bit off.
Let me see what can be done 👍

**Comment by searchy2** [comment]
For the tapping, I just mean that the button could act like a regular button. No animation or anything, just accept a tap event.
