### ISSUE TITLE
Reset button

### ISSUE THREAD

**Issue by gibus27** [shadowfaxtech/proSwipeButton#10]
Ok, the proSwipeBtn.showResultIcon(false); function can reset the swipe button but this is strange.
When the asyncTask is correct, we send proSwipeBtn.showResultIcon(true); with  the check icon, and after some time we send proSwipeBtn.showResultIcon(false); and at that point, the red error icon appears, which is rather destabilizing. It would be nice to have a real proSwipe Button reset function.
Thank you very much in anticipation for your help and your reply
Alain

**Comment by ishaangarg** [comment]
#8 Please refer this issue
Will add feature soon, thanks!
