### ISSUE TITLE
I dont the image After the swipe is done

### ISSUE THREAD

**Issue by gunnerparag** [shadowfaxtech/proSwipeButton#21]
Hi Shadowfaxtech I dont need the image for the revolving image and dont need at all. Can you please help

**Comment by ishaangarg** [comment]
`proSwipeBtn.setOnSwipeListener(new ProSwipeButton.OnSwipeListener() {
            @Override
            public void onSwipeConfirm() {
                // user has swiped the btn. Perform your sync operation now
                proSwipeBtn.showResultIcon(true); // false if task failed
            }
        });`

This will show success icon without showing progress bar.

If you dont need even that image, try this lib: https://github.com/ebanx/swipe-button

**Comment by gunnerparag** [comment]
Actually nor Do I need the image nor the progress bar can you help with that

**Comment by ishaangarg** [comment]
This library is suited for when you need a progress bar for your async operations, otherwise if you just need a swipe button, try this lib: https://github.com/ebanx/swipe-button
