### ISSUE TITLE
Reset to original state.

### ISSUE THREAD

**Issue by MAdnanIjaz** [shadowfaxtech/proSwipeButton#23]
If operation is successful then it should reverse the button just like if the case is unsuccessful. 
"https://github.com/shadowfaxtech/proSwipeButton/issues/8"
No solution yet? And can we use it for commercial with your license?

**Comment by ishaangarg** [comment]
The solution is posted on the thread, "Use the new method .showResultIcon(boolean isSuccess, boolean shouldReset)
set shouldReset to TRUE to expand the button back."

And yes you can use commercially or in any way you want 😁

**Comment by MAdnanIjaz** [comment]
implementation 'in.shadowfax:proswipebutton:1.1'
I am using this dependency and there is no method in this Like:
" swipeButton.showResultIcon(true, true);"
Its not working

**Comment by MAdnanIjaz** [comment]
> The solution is posted on the thread, "Use the new method .showResultIcon(boolean isSuccess, boolean shouldReset)
> set shouldReset to TRUE to expand the button back."
> 
> And yes you can use commercially or in any way you want 😁

implementation 'in.shadowfax:proswipebutton:1.1'
I am using this dependency and there is no method in this Like:
" swipeButton.showResultIcon(true, true);"
Its not working
Thanks for response :)

**Comment by ishaansrm** [comment]
The latest release is v1.2.2
so use this:
`implementation 'in.shadowfax:proswipebutton:1.2.2'`

Check releases page for changelog: https://github.com/shadowfaxtech/proSwipeButton/releases

**Comment by ishaangarg** [comment]
The latest release is v1.2.2
so use this:
implementation 'in.shadowfax:proswipebutton:1.2.2'

Check releases page for changelog: https://github.com/shadowfaxtech/proSwipeButton/releases
