### ISSUE TITLE
Reverse function

### ISSUE THREAD

**Issue by lorensoftware** [shadowfaxtech/proSwipeButton#26]
How can I activate the reverse function for swipe (right to left instead of left to right)? In issue #6 is not specified

**Comment by ishaangarg** [comment]
The lib doesn't support RTL at the moment. We'll be adding support soon.

In the meanwhile, you can checkout https://github.com/jefryjacky/proSwipeButton which is a fork of this repo with reverse functionality for RTL support.

For further discussion on RTL support, plz comment on issue #6
