### ISSUE TITLE
customizing the swipe distance

### ISSUE THREAD

**Issue by AhmedBassiouny** [shadowfaxtech/proSwipeButton#3]
The button works GREAT!! thanks a lot
But the only thing that keeping us from using it is that the user has to swipe for a long distance which is a little annoying.

Would love if we can change the **0.85** percentage in this line:
`if (arrowHintContainer.getX() + arrowHintContainer.getWidth() > getWidth() * 0.85)`

**Comment by ishaangarg** [comment]
Thanks for the suggestion! Will add this option in the next release :+1:

**Comment by ishaangarg** [comment]
Added in release 1.0.2
