### ISSUE TITLE
Need for a reset function

### ISSUE THREAD

**Issue by rittermobile** [shadowfaxtech/proSwipeButton#8]
There is not method to reset the proSwipeButton. Once the full swipe has ended the button can not be reseted to the original state. This means every button can only be used once.

**Comment by ishaangarg** [comment]
If you call showResult(false) on the button, it will animate back to original state for retrying.
However if you call showResult(true), then the button animates to a tick icon & we assume that another activity/frag/dialog or screen will open up after that.

I'm curious to know in what use case you would require the button to return to original state after successfully completing its operation. Becaase then the user can swipe the button again.

**Comment by rittermobile** [comment]
In my case I don't open another activity or fragment. The user can use the button several times to open a container because the container closes automatically. Calling  `showResultIcon(false)` shows the false icon which is not desired. 

Here is the use case:
User swipes the button 
Apps connects to container 
App send open container
Container opens and then closes automatically
=> User wants to do the same procedure again

**Comment by ishaangarg** [comment]
I see. Will add feature in next release.
Thanks a lot for the suggestion!

**Comment by ishaangarg** [comment]
#11 
Use the new method ```.showResultIcon(boolean isSuccess, boolean shouldReset)```
set shouldReset to TRUE to expand the button back.

The old method ```.showResultIcon(boolean isSuccess)``` will continue to work as before.

Thanks for the suggestion :+1:
